DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS djs;


CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username varchar(255) UNIQUE NOT NULL,
  password varchar(255) NOT NULL,
  type varchar(255) NOT NULL
);

CREATE TABLE bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  booker_id INTEGER NOT NULL,
  dj_id INTEGER NOT NULL,
  created DATE NOT NULL DEFAULT CURRENT_DATE,
  bookedfor DATE NOT NULL DEFAULT CURRENT_DATE,
  FOREIGN KEY (booker_id) REFERENCES users(id)
  FOREIGN KEY (dj_id) REFERENCES djs(id)
);

CREATE TABLE djs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  bio varchar(800),
  genres varchar(255),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

